<a href="https://colab.research.google.com/github/dhar9571/python_revision/blob/main/python_revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basics

## Strings - 5

Strings are used in Python to record text information, such as names. It could either be a word, a phrase, a sentence, a paragraph or an entire encyclopedia.

Strings are immutable which means once assigned, the elements of a strings cannot be changed

In [ ]:
# Single word
my_first_string= 'algebra'
my_first_string

'algebra'

In [ ]:
# Entire phrase
phrase = 'Statistics sits at the heart of machine learning'
print(phrase)

Statistics sits at the heart of machine learning


In [ ]:
my_first_string[1]

'l'

Strings do not support item assignments

In [ ]:
my_first_string[:3]

'alg'

#### Functions and Methods:

lower() method converts the string to uppercase

In [ ]:
phrase.lower()

'statistics sits at the heart of machine learning'

upper() method converts the string to uppercase

In [ ]:
phrase.upper()

'STATISTICS SITS AT THE HEART OF MACHINE LEARNING'

len returns length of the string

In [ ]:
len(phrase)

48

count counts the total number of given in a string

In [ ]:
phrase.count('si')

1

find() method returns the index of the first occurrence of a string present in a given string

In [ ]:
phrase.find('si')

11

replace() method takes two arguments - (i) the string to replace and (ii) the string to replace with, and returns a modified string after the operation

In [ ]:
print(phrase)

Statistics sits at the heart of machine learning


In [ ]:
phrase.replace('Statistics', 'maths')

'maths sits at the heart of machine learning'

Check if a string contains a particular word or character

In [ ]:
'maths' in phrase

False

##Lists

Lists can be thought of the most general version of a sequence in Python.

Unlike strings, they are mutable, meaning the elements inside a list can be changed!

Lists are constructed with brackets [] and commas separating every element in the list.

In [ ]:
# Assign a list to an variable named my_list
my_list = [1,2,3,4]

In [ ]:
type(my_list)

list

In [ ]:
my_list = ['A string',23,100.232,'o',True]

In [ ]:
# Consider a list of strings
loss_functions = ['Mean Absolute Error','Mean Squared Error','Huber Loss','Log Loss','Hinge Loss']
print(loss_functions)

['Mean Absolute Error', 'Mean Squared Error', 'Huber Loss', 'Log Loss', 'Hinge Loss']


In [ ]:
# Grab the element at index 0, which is the FIRST element
print(loss_functions[0])

Mean Absolute Error


In [ ]:
# lists concatination

loss_functions = loss_functions + ['Root Mean Squared Error']
print(loss_functions)

['Mean Absolute Error', 'Mean Squared Error', 'Huber Loss', 'Log Loss', 'Hinge Loss', 'Root Mean Squared Error']


In [ ]:
loss_functions[::-1]

['Root Mean Squared Error',
 'Log Loss',
 'Huber Loss',
 'Mean Squared Error',
 'Mean Absolute Error']

In [ ]:
# list multiplication:

loss_functions*2

['Mean Absolute Error',
 'Mean Squared Error',
 'Huber Loss',
 'Log Loss',
 'Hinge Loss',
 'Root Mean Squared Error',
 'Mean Absolute Error',
 'Mean Squared Error',
 'Huber Loss',
 'Log Loss',
 'Hinge Loss',
 'Root Mean Squared Error']

### Functions and Methods

len() function returns the length of the list

In [ ]:
len(loss_functions)

6

min() function returns the minimum element of the list

min() function only works with lists of similar data types

In [ ]:
new_list = [6, 9, 1, 3, 5.5]
min(new_list)

1

max() function returns the maximum element of the list

max() function only works with lists of similar data types

In [ ]:
max(new_list)

9

sum() function returns the sum of the elements of the list

sum() function only works with lists of numeric data types

In [ ]:
sum(new_list)

24.5

sorted() function returns the sorted list

sorted() function takes reverse boolean as an argument

sorted() function only works on a list with similar data types

sorted() function does not change our list

In [ ]:
sorted(new_list, reverse=False)

[1, 3, 5.5, 6, 9]

Use the append() method to permanently add an item to the end of a list.

append() method takes the element which you want to add to the list as an argument

In [ ]:
print(new_list)
new_list.append('come on')
print(new_list)

[6, 9, 1, 3, 5.5]
[6, 9, 1, 3, 5.5, 'come on']


In [ ]:
new_list.append([1,2,3])
print(new_list)

[6, 9, 1, 3, 5.5, 'come on', [1, 2, 3]]


Use the extend() method to merge a list to an existing list

extend() method takes a list or any iterable as an argument.


In [ ]:
new_list.extend([7,8,9])
print(new_list)

[6, 9, 1, 3, 5.5, 'come on', [1, 2, 3], 7, 8, 9]


Use pop() to "pop off" an item from the list.

By default pop() takes off the element at the last index, but you can also specify which index to pop off.

pop() takes the index as an argument and returns the elenent which was popped off.

In [ ]:
new_list.pop()
print(new_list)

[6, 9, 1, 3, 5.5, 'come on', [1, 2, 3], 7]


In [ ]:
new_list.pop(0)
print(new_list)

[9, 1, 3, 5.5, 'come on', [1, 2, 3], 7]


Use remove() to remove an item/element from the list.

By default remove() removes the specified element from the list.

remove() takes the element as an argument.

In [ ]:
new_list.remove('come on')
print(new_list)

[9, 1, 3, 5.5, [1, 2, 3], 7]


In [ ]:
new_list.remove([1,2,3])
print(new_list)

[9, 1, 3, 5.5, 7]


The count() method returns the total occurrence of a specified element in the list

In [ ]:
new_list.count(5.5)

1

The index() method returns the index of a specified element.

In [ ]:
my_list = [1, 2, 3, 1, 1, 1, 3, 10, 5, 8, 'Append me!', 2.73, 'Wubba']
my_list.index('Wubba')

12

In [ ]:
my_list.index(2.73)

11

Use sort() to sort the list in either ascending/descending order

The sorting is done in ascending order by default

sort() method takes the reverse boolean as an argument

sort() method only works on a list with elements of same data type

In [ ]:
new_list = [6, 9, 1, 3, 5]

new_list.sort()
print(new_list)

[1, 3, 5, 6, 9]


reverse() method reverses the list

In [ ]:
new_list.reverse()
print(new_list)

[9, 6, 5, 3, 1]


In [ ]:
# Nested List i.e. List of Lists

# Let's make three lists
lst_1=[1,2,3]
lst_2=['b','a','d']
lst_3=[7,8,9]

# Make a list of lists to form a matrix
list_of_lists = [lst_1,lst_2,lst_3]

print(list_of_lists)

[[1, 2, 3], ['b', 'a', 'd'], [7, 8, 9]]


In [ ]:
# indexing in nested list:

list_of_lists[1][1]

'a'

## Tuples

In Python tuples are very similar to lists, however, unlike lists they are immutable meaning they can not be changed.

You would use tuples to present things that shouldn't be changed, such as days of the week, or dates on a calendar.

In [ ]:
# Create a tuple
my_tuple = (1,'a',3)
my_tuple

(1, 'a', 3)

In [ ]:
# create empty tuple

empty_tuple = ()

In [ ]:
empty_tuple

()

In [ ]:
# indexing

my_tuple[1]

'a'

In [ ]:
# tupe_of_tuple

tupe_of_tuple = ((1,2),(3,4))
print(tupe_of_tuple)

((1, 2), (3, 4))


### Functions and Methods

The index() method returns the index of a specified element

In [ ]:
my_tuple.index('a')

1

The count() method returns the total occurrence of a specified element in a tuple

In [ ]:
my_tuple.count(1)

1

In [ ]:
# Immutability

my_tuple[0] = 'change'

TypeError: ignored

Tuple does not support methods such as append(), extend(), remove(), pop()

In [ ]:
# zip() function takes multiple lists/tuples as arguments and zips them together
# This function returns a list of n-paired tuples where n is the number of lists being zipped

city_list = ('Delhi','Patna','Cuttack','Guwahati')
river_list = ('Yamuna','Ganga','Mahanadi','Brahmaputra')

city_river = tuple(zip(city_list, river_list))

print(city_river)

(('Delhi', 'Yamuna'), ('Patna', 'Ganga'), ('Cuttack', 'Mahanadi'), ('Guwahati', 'Brahmaputra'))


## Sets

Sets are an unordered collection of unique elements. We can construct them by using the set() function.

Sets cannot have duplicates.

Sets are mutable just like lists.

You can create a non-empty set with curly braces by specifying elements separated by a comma.

In [ ]:
# Create an empty set
empty_set = set()

In [ ]:
# casting a list for unique elements

list1 = [1,4,5,2,4,6,4,3,5,6,4,3,5,7,6,5,4]

set1 = set(list1)
print(set1)

{1, 2, 3, 4, 5, 6, 7}


In [ ]:
# A set cannot have mutable items
my_set = {1, 2, (3, 4)}

In [ ]:
print(my_set)

{1, 2, (3, 4)}


We cannot have lists as an element in a set.

We can have tuples as an element in a set.

We cannot have set as an element in a set.

In [ ]:
my_set = {1,2, [3,5]}

TypeError: ignored

In [ ]:
my_set = {1,2, (3,5)}

In [ ]:
my_set = {1,2, {3,5}}

TypeError: ignored

In [ ]:
# we can have set with different dtypes

new_set = {1,2,3,'a'}
print(new_set)

{'a', 1, 2, 3}


### Function and Methods

add() method adds an element to a set

This method takes the element to be added as an argument

In [ ]:
print(set1)

set1.add(8)

print(set1)

{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7, 8}


update() method helps to add multiple elements to a set

In [ ]:
set1.update([9,10,11])
print(set1)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}


Use remove() to remove an item/element from the set.

By default remove() removes the specified element from the set.

remove() takes the element as an argument.

In [ ]:
set1.remove(9)
print(set1)

{1, 2, 3, 4, 5, 6, 7, 8, 10, 11}


union() method returns the union of two sets

Also denoted by the operator |

In [ ]:
# Initialize sets A and B
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}

A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
A|B

{1, 2, 3, 4, 5, 6, 7, 8}

intersection() method returns the intersection of two sets

Also denoted by the operator &

In [ ]:
A.intersection(B)

{4, 5}

In [ ]:
A&B

{4, 5}

difference() method returns the difference of two sets

Difference of the set B from set A i.e, (A - B) is a set of elements that are only in A but not in B

Also denoted by the operator -

In [ ]:
A.difference(B)

{1, 2, 3}

In [ ]:
A-B

{1, 2, 3}

symmetric_difference() method returns the set of elements in A and B but not in both (excluding the intersection)

Also denoted by the operator ^

In [ ]:
A.symmetric_difference(B)

{1, 2, 3, 6, 7, 8}

In [ ]:
A^B

{1, 2, 3, 6, 7, 8}

## Dictionary

A Python dictionary consists of a key and then an associated value. That value can be almost any Python object. So a dictionary object always has elements as key-value pairs

A dictionary object is constructed using curly braces {key1:value1,key2:value2,key3:value3}

In [ ]:
# Make a dictionary with {} and : to signify a key and a value
marvel_dict = {'Name':'Thor','Place':'Asgard','Weapon' : 'Hammer', 1:2, 3 : 'power', 'alibies' : ['Ironman','Captain America'], 'abc' : {1:2, 4:5}}

In [ ]:
# We can call value by it's key:

marvel_dict['Name']

'Thor'

In [ ]:
marvel_dict["alibies"][0]

'Ironman'

### Functions and Methods:

keys() method returns the list of keys in the dictionary object

In [ ]:
marvel_dict.keys()

dict_keys(['Name', 'Place', 'Weapon', 1, 3, 'alibies', 'abc'])

values() method returns the list of values in the dictionary object

In [ ]:
marvel_dict.values()

dict_values(['Thor', 'Asgard', 'Hammer', 2, 'power', ['Ironman', 'Captain America'], {1: 2, 4: 5}])

items() method returns the list of the keys and values (seperated by commas in tuple)

In [ ]:
marvel_dict.items()

dict_items([('Name', 'Thor'), ('Place', 'Asgard'), ('Weapon', 'Hammer'), (1, 2), (3, 'power'), ('alibies', ['Ironman', 'Captain America']), ('abc', {1: 2, 4: 5})])

get() method takes the key as an argument and returns None if the key is not found in the dictionary.

We can also set the value to return if a key is not found. This will be passed as the second argument in get()

In [ ]:
marvel_dict.get('power','not found')

'not found'

In [ ]:
marvel_dict.get('power')

Its important to note that dictionaries are very flexible in the data types they can hold. For example:

In [ ]:
employee_dict = {'Name':'Sanket','Skills':['Python','Machine Learning','Deep Learning'],'Band':6.0,'Promotion Year':[2016,2018,2020]}

len() function provides the number of keys or values inside the dictionary

In [ ]:
len(marvel_dict)

7

update()

You can add an element which is a key-value pair using the update() method

This method takes a dictionary as an argument

We can also use the update() method to update the existing values for a key

In [ ]:
marvel_dict.update({'friend':'hulk'})
marvel_dict

{'Name': 'Thor',
 'Place': 'Asgard',
 'Weapon': 'Hammer',
 1: 2,
 3: 'power',
 'alibies': ['Ironman', 'Captain America'],
 'abc': {1: 2, 4: 5},
 'friend': 'hulk'}

dict()

We can also create dictionary objects from sequence of items which are pairs.

This is done using the dict()method

dict() function takes the list of paired elements as argument

In [ ]:
country_list = ['India','Australia','United States','England']
city_list = ['New Delhi', 'Canberra' , 'Washington DC','London']

dict_of_countries = dict(zip(country_list, city_list))

print(dict_of_countries)

{'India': 'New Delhi', 'Australia': 'Canberra', 'United States': 'Washington DC', 'England': 'London'}


pop() method removes and returns an element from a dictionary having the given key.

This method takes two arguments/parameters (i) key - key which is to be searched for removal, (ii) default - value which is to be returned when the key is not in the dictionary



In [ ]:
dict_of_countries.pop('England')

'London'

In [ ]:
dict_of_countries

{'India': 'New Delhi',
 'Australia': 'Canberra',
 'United States': 'Washington DC'}

In [ ]:
[(i, j) for i, j in dict_of_countries.items()]

[('India', 'New Delhi'),
 ('Australia', 'Canberra'),
 ('United States', 'Washington DC')]

## for loops

A <code>for</code> loop acts as an iterator in Python; it goes through items that are in a *sequence* or any other iterable item. Iterable is an object, which one can iterate over. Objects that we've learned about that we can iterate over include strings, lists, tuples, and even built-in iterables for dictionaries, such as keys or values.

Here's the general format for a <code>for</code> loop in Python:

    for item in object:
        statements to do stuff

In [ ]:
# Consider a list of strings

got_houses = ['Stark', 'Arryn', 'Baratheon', 'Tully', 'Greyjoy', 'Lannister', 'Tyrell', 'Martell', 'Targaryen']

for i in got_houses:
  print(i)

Stark
Arryn
Baratheon
Tully
Greyjoy
Lannister
Tyrell
Martell
Targaryen


Another interesting way to loop through the elements of a list is to use the enumerate() function. Using enumerate requires us two iterators index and element

In [ ]:
got_houses = ['Stark', 'Arryn', 'Baratheon', 'Tully', 'Greyjoy', 'Lannister', 'Tyrell', 'Martell', 'Targaryen']

for i, j in enumerate(got_houses):
  print(i, j)

0 Stark
1 Arryn
2 Baratheon
3 Tully
4 Greyjoy
5 Lannister
6 Tyrell
7 Martell
8 Targaryen


range() function is a pretty useful function to get a sequence of numbers. It takes three arguments : start, stop, step

In [ ]:
# Let us first print the squares
for number in range(0,10,2):
  squared_number = number**2
  print(f"The square of {number} is {squared_number}")

The square of 0 is 0
The square of 2 is 4
The square of 4 is 16
The square of 6 is 36
The square of 8 is 64


## <u>While Loops </u>

### The <code>while</code> statement in Python is one of the most general ways to perform iteration. A <code>while</code> statement will repeatedly execute a single statement or group of statements as long as the condition is true. The reason it is called a 'loop' is because the code statements are looped through over and over again until the condition is no longer met.

### The general format of a while loop is:

    while test:
        code statements
    else:
        final code statements

### Let’s look at a few simple <code>while</code> loops in action.

In [ ]:
x = 0

while x < 10:
  print('x is currently: ',x)
  print('x is still less than 10, adding 1 to x')
  x=x+1

x is currently:  0
x is still less than 10, adding 1 to x
x is currently:  1
x is still less than 10, adding 1 to x
x is currently:  2
x is still less than 10, adding 1 to x
x is currently:  3
x is still less than 10, adding 1 to x
x is currently:  4
x is still less than 10, adding 1 to x
x is currently:  5
x is still less than 10, adding 1 to x
x is currently:  6
x is still less than 10, adding 1 to x
x is currently:  7
x is still less than 10, adding 1 to x
x is currently:  8
x is still less than 10, adding 1 to x
x is currently:  9
x is still less than 10, adding 1 to x


## break, continue, pass

### We can use <code>break</code>, <code>continue</code>, and <code>pass</code> statements in our loops to add additional functionality for various cases. The three statements are defined by:

    break: Breaks out of the current closest enclosing loop.
    continue: Goes to the top of the closest enclosing loop.
    pass: Does nothing at all.
    
    
### Thinking about <code>break</code> and <code>continue</code> statements, the general format of the <code>while</code> loop looks like this:

    while test:
        code statement
        if test:
            break
        if test:
            continue
    else:

### <code>break</code> and <code>continue</code> statements can appear anywhere inside the loop’s body, but we will usually put them further nested in conjunction with an <code>if</code> statement to perform an action based on some condition.


In [ ]:
x = 0

while x < 10:
  print('x is currently: ',x)
  print(' x is still less than 10, adding 1 to x')
  x+=1
  if x==3:
    print('x==3')
    break
  else:
    print('continuing...')
    continue

x is currently:  0
 x is still less than 10, adding 1 to x
continuing...
x is currently:  1
 x is still less than 10, adding 1 to x
continuing...
x is currently:  2
 x is still less than 10, adding 1 to x
x==3


## List Comprehensions

List comprehensions are a tool for transforming one list (any iterable actually) into another list. During this transformation, elements can be conditionally included in the new list and each element can be transformed as needed.
List comprehensions in Python are great, but mastering them can be tricky because they don’t solve a new problem: they just provide a new syntax to solve an existing problem.

In [ ]:
# The list of numbers
list_of_numbers = [1, 2, 4, 6, 11, 14, 17, 20]

# Let us first initialize a list where we will be appending the squares in each iteration

squared_numbers = []

for number in list_of_numbers:
  # Use the append method to add the numbers one by one to our list
  squared_numbers.append(number**2)
  # print(squared_numbers)

print(f"The list of squared numbers is {squared_numbers}")

The list of squared numbers is [1, 4, 16, 36, 121, 196, 289, 400]


In [ ]:
# Getting the list of squares using list comprehension
squared_numbers = [number**2 for number in list_of_numbers]
print(squared_numbers)

[1, 4, 16, 36, 121, 196, 289, 400]


Suppose we wanted to get the squares of only those numbers which are even

In [ ]:
print([number**2 for number in list_of_numbers if number%2==0])

[4, 16, 36, 196, 400]


In [ ]:
print([number**2 if number%2==0 else number**5 for number in list_of_numbers])

[1, 4, 16, 36, 161051, 196, 1419857, 400]


**A list comprehension consists of the following parts:**

An Input Sequence.

A Variable representing members of the input sequence.

An Optional Predicate expression.

An Output Expression producing elements of the output list from members of the Input Sequence that satisfy the predicate.

# Numpy

**Python Module:**

A Python module is like a small, self-contained file that contains Python code.

It can include functions, variables, and classes that you can use in your Python programs.

Modules are designed to help organize your code and make it more manageable.

For example, if you have a module named "math_operations.py," it might contain functions for doing math operations like addition, subtraction, etc.


**Python Library:**

A Python library is a collection of modules bundled together to solve specific tasks or provide functionality for various purposes.

Libraries are like toolkits that contain pre-written code to help you accomplish common tasks without having to write everything from scratch.

Python has a rich ecosystem of libraries, such as NumPy for numerical operations, pandas for data manipulation, and matplotlib for creating plots and charts.

Libraries are typically maintained by the Python community or other developers and can be easily installed and used in your Python programs.

NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array. The NumPy package is the workhorse of data analysis, machine learning, and scientific computing in the python ecosystem. It vastly simplifies manipulating and crunching vectors and matrices. Some of python’s leading package rely on NumPy as a fundamental piece of their infrastructure (examples include scikit-learn, SciPy, pandas, and tensorflow). Beyond the ability to slice and dice numeric data, mastering numpy will give you an edge when dealing and debugging with advanced usecases in these libraries.

In [ ]:
# Statement to import the numpy library
import numpy as np

One-dimensional array of some prime numbers

In [ ]:
prime_array = np.array([2,3,5,7,11])
print(prime_array)
print(prime_array.shape)

[ 2  3  5  7 11]
(5,)


Create a two-dimensional array

In [ ]:
another_array = np.array([[1,2],[3,4]])
print(another_array)
print(another_array.shape)

[[1 2]
 [3 4]]
(2, 2)


Create a three-dimensional array

In [ ]:
threeD_array = np.array([[[1,2],[3,4]],
                        [[5,6],[7,8]]])
print(threeD_array)
print(threeD_array.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


Create n-dimensional array

In [ ]:
n_dimensional = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],
          [[[1,2],[3,4]],[[5,6],[7,8]]]])

print(n_dimensional)
print(n_dimensional.shape)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
(2, 2, 2, 2)


### A numpy array has following attributes

ndarray.shape

ndarray.ndim

ndarray.size

ndarray.dtype

ndarray.astype

ndarray.shape

This returns a tuple consisting of array dimensions and can be used to resize the array

In [ ]:
alma_array = np.array([[1,2,3],[4,5,6]])
print(alma_array.shape)

(2, 3)


ndarray.ndim

This returns the number of dimensions

In [ ]:
array_of_integers = np.array([0,1,2,3,4,5,6,7,8,9])
print("Dimensions of 'array_of_integers' = ", array_of_integers.ndim)

sample_2d_array = np.array([[1,2,3],[4,5,6]])
print("Dimensions of 'sample_2d_array' = ", sample_2d_array.ndim)

Dimensions of 'array_of_integers' =  1
Dimensions of 'sample_2d_array' =  2


ndarray.size

This returns the total number of elements in the array

In [ ]:
# Print the size of array
array_of_integers = np.array([0,1,2,3,4,5,6,7,8,9])
print(f"The total number of elements in our array 'array_of_integers' =  {array_of_integers.size}")

sample_2d_array = np.array([[1,2,3],[4,5,6]])
print(f"The total number of elements in our array 'sample_2d_array' =  {sample_2d_array.size}")

The total number of elements in our array 'array_of_integers' =  10
The total number of elements in our array 'sample_2d_array' =  6


ndarray.dtype

This returns the data type of the array

In [ ]:
# Print the dtype of array
my_array = np.array([1,2,3,4,5])
print(my_array.dtype)

int64


In [ ]:
# Print the dtype of another array
my_array = np.array([1,2.0,3,4,5,'abc'])
print(my_array.dtype)

<U32


ndarray.astype

This changes the data type of an array

In [ ]:
# Create an array
arravali = np.array([2,3,4])
print(arravali)
print(arravali.dtype)

# Change the datatype of the array to float
arravali_ = arravali.astype('float64')
print(arravali_)
print(arravali_.dtype)

[2 3 4]
int64
[2. 3. 4.]
float64


### Why to choose Numpy

**Numpy data structures perform better in:**

Memory - Numpy data structures take up less space

Performance - they have a need for speed and are faster than lists

Functionality - SciPy and NumPy have optimized functions such as linear algebra operations built in.

### Different ways of creating an ndarray

Uninitialized

In [ ]:
# Creating an uninitialized array of a specified shape
uninitialized_array = np.empty([5,3],dtype=int)
print(uninitialized_array)

[[    138530228448592     100454228988208                   0]
 [                  0     138529875165184 8319683848551211643]
 [3180222411935070754 8391722768137527840 7959390389040738153]
 [2318290808525693556 8675445202132104482 7957695011165139568]
 [2318365875964093043 7233184988217307170                 128]]


Initialized with zeros

In [ ]:
zero_array = np.zeros([5,3], dtype=int)
print(zero_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Initialized with ones

In [ ]:
ones_array = np.ones([5,3], dtype=int)
print(ones_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


Array from numerical ranges

Array with values from 0 to N

In [ ]:
array_with_range = np.arange(5)
array_with_range

array([0, 1, 2, 3, 4])

In [ ]:
# Set start and stop parameters
# Parameters for the function - np.arange(start, stop, step, dtype)
# Default dtype is that of the input given
another_array_with_range = np.arange(10,20,2)
another_array_with_range

array([10, 12, 14, 16, 18])

to get the number of evenly spaced values between intervals

In [5]:
# Parameters for the function - np.linespace(start, stop, num, endpoint, retstep, dtype)
# dtype is that of output array
linearly_spaced_values = np.linspace(10,20,9 , endpoint = False, retstep = True)
linearly_spaced_values

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889]),
 1.1111111111111112)

In [ ]:
# to get the number of evenly spaced values between intervals
# Parameters for the function - np.linespace(start, stop, num, endpoint, retstep, dtype)
# dtype is that of output array
linearly_spaced_values = np.linspace(1, 100, 10, endpoint= True, retstep=True)
linearly_spaced_values

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

Array from random numbers

to get an array with random input elements of desired shape

In [9]:
np.random.random((5,3))

array([[8.22991407e-01, 8.64686522e-01, 4.15230747e-01],
       [2.88701255e-01, 6.29099001e-01, 6.76434268e-04],
       [1.48612976e-01, 6.55778085e-01, 7.05588097e-01],
       [5.03568723e-01, 4.24218968e-01, 4.05482413e-01],
       [9.88543882e-01, 2.13336143e-01, 7.70846859e-01]])

to get an array with random input elements of desired shape

In [10]:
np.random.randint(1,6,(5,3))

array([[4, 3, 3],
       [2, 3, 5],
       [5, 5, 3],
       [5, 1, 2],
       [2, 2, 1]])

Array from specified numbers

To get an array with specified input element of desired shape

In [11]:
np.full((5,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [12]:
a = np.ones((3,3))*30
print(a)

[[30. 30. 30.]
 [30. 30. 30.]
 [30. 30. 30.]]


to get an identity matrix

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Manipulation

np.transpose(array) - To transpose array

np.reshape(array,shape) - To Change shape of an array

np.resize(array,shape) - To return new array with shape

np.flatten(array) - To flatten the array

np.transpose()

Transpose is defined as an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix A by producing another matrix, often denoted by  AT

In [16]:
arr1 = np.random.randint(1,6,(3,5))

print(arr1)

[[3 3 5 3 1]
 [2 4 5 2 4]
 [2 1 5 4 4]]


In [17]:
print(np.transpose(arr1))

[[3 2 2]
 [3 4 1]
 [5 5 5]
 [3 2 4]
 [1 4 4]]


np.reshape(shape)

Gives a new shape to an array without changing its data.

In [19]:
arr2 = np.random.randint(1,6,(3,5,2))
print(arr2)
print(arr2.shape)

[[[1 1]
  [4 5]
  [5 4]
  [2 1]
  [4 4]]

 [[3 5]
  [3 1]
  [3 3]
  [3 2]
  [1 5]]

 [[3 4]
  [2 2]
  [5 5]
  [2 5]
  [1 4]]]
(3, 5, 2)


In [20]:
arr2_reshaped = arr2.reshape(5,2,3)
print(arr2_reshaped)
print(arr2_reshaped.shape)

[[[1 1 4]
  [5 5 4]]

 [[2 1 4]
  [4 3 5]]

 [[3 1 3]
  [3 3 2]]

 [[1 5 3]
  [4 2 2]]

 [[5 5 2]
  [5 1 4]]]
(5, 2, 3)


np.resize(shape)

Changes shape and size of array in-place.

In [21]:
# Intialize a 3D array
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[20 28 39 26 10 12]
  [17 34 26 20 24 15]
  [36 16 20 24 30 12]
  [13 12 44 36 15 27]]

 [[18 32 42 24 16 10]
  [29 30 36 36 40 31]
  [29 14 21 18 12 43]
  [29 35 15 14 41 10]]]
 
 The shape of the array is (2, 4, 6)


In [22]:
# Resize the created 3D array
new_shape = (4,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"The resized array is \n{resized_random_3D_cohort}")
print(f" \n The shape of the array is {resized_random_3D_cohort.shape}")

The resized array is 
[[[20 28 39 26 10 12]
  [17 34 26 20 24 15]
  [36 16 20 24 30 12]]

 [[13 12 44 36 15 27]
  [18 32 42 24 16 10]
  [29 30 36 36 40 31]]

 [[29 14 21 18 12 43]
  [29 35 15 14 41 10]
  [20 28 39 26 10 12]]

 [[17 34 26 20 24 15]
  [36 16 20 24 30 12]
  [13 12 44 36 15 27]]]
 
 The shape of the array is (4, 3, 6)


np.flatten()

Returns flattened 1D arrays

In [24]:
np.random.randint(1,6, (3,5)).flatten()

array([1, 3, 3, 1, 5, 3, 2, 4, 3, 1, 3, 2, 3, 5, 3])

Difference between copy and view

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In [25]:
# Lets take an example of a list
a = [1,2,3]
b = a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [26]:
# Lets use the copy method
a = [1,2,3]
b = a.copy()
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


**Basic Operations & Functions**

np.add() - Adding two arrays

np.subtract() - Subtracting two arrays

np.multiply() - Multiplying two arrays

np.divide() - Dividing two arrays

np.sum() - Sum of items in an array

np.min() - Minimum of items in an array

np.max() - Minimum of items in an array

np.mean() - Mean of items in an array

np.sort() - Sorting an array

In [27]:
# np.add()

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.add(a, b)
print(result)  # Output: [5 7 9]

[5 7 9]


In [28]:
# np.subtract()

a = np.array([7, 8, 9])
b = np.array([4, 5, 6])
result = np.subtract(a, b)
print(result)  # Output: [3 3 3]

[3 3 3]


In [29]:
# np.multiply()

a = np.array([2, 3, 4])
b = np.array([5, 6, 7])
result = np.multiply(a, b)
print(result)  # Output: [10 18 28]

[10 18 28]


In [30]:
# np.divide()

a = np.array([10, 15, 20])
b = np.array([2, 3, 4])
result = np.divide(a, b)
print(result)  # Output: [5. 5. 5.]

[5. 5. 5.]


In [31]:
# np.sum()

arr = np.array([1, 2, 3, 4, 5])
result = np.sum(arr)
print(result)  # Output: 15

15


In [32]:
# np.min()

arr = np.array([5, 2, 9, 1, 7])
result = np.min(arr)
print(result)  # Output: 1

1


In [34]:
# np.max()

arr = np.array([5, 2, 9, 1, 7])
result = np.max(arr)
print(result)  # Output: 9

9


In [35]:
# np.mean()

arr = np.array([2, 4, 6, 8, 10])
result = np.mean(arr)
print(result)  # Output: 6.0

6.0


In [36]:
# np.sort()

arr = np.array([5, 2, 9, 1, 7])
result = np.sort(arr)
print(result)  # Output: [1 2 5 7 9]

[1 2 5 7 9]


**The concept of Broadcasting**

Broadcasting allows these types of binary operations to be performed on arrays of different sizes–for example, we can just as easily add a scalar (think of it as a zero-dimensional array) to an array:

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

**Rule 1**: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

**Rule 2**: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

**Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

Broadcasting scalar to an array

In [37]:
a = np.array([1, 2, 3])
scalar = 2
result = a * scalar  # The scalar is broadcast to match the shape of 'a'
print(result)  # Output: [2 4 6]

[2 4 6]


Broadcasting a smaller array to a larger array

In [40]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
result = a + b  # 'b' is broadcast to match the shape of 'a'
print(result)

[[11 22 33]
 [14 25 36]]


Broadcasting along multiple dimensions

In [39]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
result = a * b  # 'b' is broadcast to match the shape of 'a' along both dimensions
print(result)  # Output: [[10 40]
               #          [30 80]]

[[10 40]
 [30 80]]


# Pandas

Pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with structured (tabular, multidimensional, potentially heterogeneous) and time series data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.

**There are two central concepts:**

**Series** : A series is essentially a column

**Data Frame** : A DataFrame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns. Pandas DataFrame consists of three principal components, the data, rows, and columns.

In [41]:
import pandas as pd

# Series with index
number_series = pd.Series([2, 3, 5, 6, 8],index=['a', 'b', 'd','e','f'],name='Number')
print(number_series)

a    2
b    3
d    5
e    6
f    8
Name: Number, dtype: int64


In [43]:
# creating a pandas dataframe:

series = np.random.randint(1,6,(3,4))

data = pd.DataFrame(series, columns = ['a', 'b', 'c', 'd'])

print(data)

   a  b  c  d
0  1  2  1  4
1  5  5  1  2
2  1  2  2  2


In [44]:
# Initialize list of lists
list_of_lists = [['Amar', 10], ['Akbar', 15], ['Anthony', 14]]

# Create the pandas DataFrame
df = pd.DataFrame(list_of_lists, columns = ['Name', 'Age'])

# Print dataframe
df

Name  Age
0     Amar   10
1    Akbar   15
2  Anthony   14

In [45]:
# Store the data in a dictionary
employee_dict = {'Employee Name':['Rajeev', 'Sumit', 'Aviral'], 'Income':[200000, 140000, 90000]}

# Create DataFrame
employee_df = pd.DataFrame(employee_dict)

# Print the dataframe
employee_df

Employee Name  Income
0        Rajeev  200000
1         Sumit  140000
2        Aviral   90000

In [46]:
# Initialise the list of dictionaries
list_of_dicts = [{'a': 1, 'b': 2, 'c':3}, {'a':10, 'b': 20, 'c': 30}]

# Create the DataFrame
df = pd.DataFrame(list_of_dicts)

# Print the dataframe
df

a   b   c
0   1   2   3
1  10  20  30

In [47]:
# What happens if the number of keys are different in the two dictionaries
list_of_dicts = [{'a': 2, 'c':3}, {'a': 10, 'b': 20, 'c': 30}]
df = pd.DataFrame(list_of_dicts, index =['first', 'second'])
df

a   c     b
first    2   3   NaN
second  10  30  20.0

We can print the indices of our dataframe using the index attribute

In [48]:
list(df.index)

['first', 'second']

**Important pandas functions**

df.head()

df.tail()

df.rename()

df.columns

df.info()

describe()

This method gives the overall descriptive summary of the dataframe. This works only for numerical columns

iloc gets rows (or columns) at particular positions in the index (so it only takes integers).

loc gets rows (or columns) with particular labels from the index.

**Unique and Missing values:**

unique()

nunique()

value_counts()

isnull()

fillna()